const val testCodeBaseDir = "./src/test/kotlin/"
const val testDataBasePath = "./stella-tests/"
const val okTestsPath = testDataBasePath + "ok/"
const val badTestsPath = testDataBasePath + "bad/"
const val FILE_EXTENSION_ST = "st"
const val FILE_EXTENSION_STELLA = "stella"
