name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Run test
        env:
          ENABLE_ONLY_SUPPORTED_TESTS: true
        run:  ./gradlew test
